export type PlaceKind = "continent" | "country" | "city";

export type Place = {
  id: string;
  name: string;
  lat: number;
  lon: number;
  kind: PlaceKind;
  parentId: string | null;
  childId: string | null;
  summary: string;
  stats: { label: string; value: string }[];
};

const LIST: Place[] = [
  {
    id: "europe",
    name: "Europe",
    lat: 50.2,
    lon: 10.4,
    kind: "continent",
    parentId: null,
    childId: "netherlands",
    summary: "From the Atlantic edge to the continental interior. Country markers sit on the globe; choose one to descend.",
    stats: [
      { label: "Tier", value: "Continent" },
      { label: "Default route", value: "Netherlands" },
    ],
  },
  {
    id: "africa",
    name: "Africa",
    lat: 2.5,
    lon: 21.5,
    kind: "continent",
    parentId: null,
    childId: "kenya",
    summary: "Equatorial and subtropical landmass. The default descent continues through Kenya to Nairobi.",
    stats: [
      { label: "Tier", value: "Continent" },
      { label: "Default route", value: "Kenya" },
    ],
  },
  {
    id: "asia",
    name: "Asia",
    lat: 34,
    lon: 100,
    kind: "continent",
    parentId: null,
    childId: "japan",
    summary: "The widest continental span in this index. Japan is the default country lock.",
    stats: [
      { label: "Tier", value: "Continent" },
      { label: "Default route", value: "Japan" },
    ],
  },
  {
    id: "north-america",
    name: "North America",
    lat: 46,
    lon: -104,
    kind: "continent",
    parentId: null,
    childId: "united-states",
    summary: "Continental view centered on the interior. Descend through the United States to a coastal city.",
    stats: [
      { label: "Tier", value: "Continent" },
      { label: "Default route", value: "United States" },
    ],
  },
  {
    id: "south-america",
    name: "South America",
    lat: -14,
    lon: -59,
    kind: "continent",
    parentId: null,
    childId: "brazil",
    summary: "Andes to the Atlantic forests. Brazil is the default country on this branch.",
    stats: [
      { label: "Tier", value: "Continent" },
      { label: "Default route", value: "Brazil" },
    ],
  },
  {
    id: "oceania",
    name: "Oceania",
    lat: -25,
    lon: 134,
    kind: "continent",
    parentId: null,
    childId: "australia",
    summary: "Australia and the south-west Pacific. The default lock is Australia, then Sydney.",
    stats: [
      { label: "Tier", value: "Continent" },
      { label: "Default route", value: "Australia" },
    ],
  },
  {
    id: "netherlands",
    name: "Netherlands",
    lat: 52.25,
    lon: 5.55,
    kind: "country",
    parentId: "europe",
    childId: "lelystad",
    summary: "Low country on the North Sea. City lights mark the Randstad and the Flevoland polder towns.",
    stats: [
      { label: "Region", value: "Western Europe" },
      { label: "Next lock", value: "Lelystad" },
    ],
  },
  {
    id: "germany",
    name: "Germany",
    lat: 51.1,
    lon: 10.4,
    kind: "country",
    parentId: "europe",
    childId: "berlin",
    summary: "Central European corridor between the North Sea and the Alps.",
    stats: [
      { label: "Region", value: "Central Europe" },
      { label: "Next lock", value: "Berlin" },
    ],
  },
  {
    id: "france",
    name: "France",
    lat: 46.6,
    lon: 2.4,
    kind: "country",
    parentId: "europe",
    childId: "paris",
    summary: "Atlantic and Mediterranean coasts with Paris as the default city lock.",
    stats: [
      { label: "Region", value: "Western Europe" },
      { label: "Next lock", value: "Paris" },
    ],
  },
  {
    id: "united-kingdom",
    name: "United Kingdom",
    lat: 54.2,
    lon: -2.6,
    kind: "country",
    parentId: "europe",
    childId: "london",
    summary: "Island state off northwest Europe. London is the default city lock.",
    stats: [
      { label: "Region", value: "Northwest Europe" },
      { label: "Next lock", value: "London" },
    ],
  },
  {
    id: "italy",
    name: "Italy",
    lat: 42.8,
    lon: 12.5,
    kind: "country",
    parentId: "europe",
    childId: "rome",
    summary: "Peninsula in the central Mediterranean.",
    stats: [
      { label: "Region", value: "Southern Europe" },
      { label: "Next lock", value: "Rome" },
    ],
  },
  {
    id: "spain",
    name: "Spain",
    lat: 40.3,
    lon: -3.7,
    kind: "country",
    parentId: "europe",
    childId: "madrid",
    summary: "Iberian plateau between the Atlantic and the Mediterranean.",
    stats: [
      { label: "Region", value: "Southwest Europe" },
      { label: "Next lock", value: "Madrid" },
    ],
  },
  {
    id: "kenya",
    name: "Kenya",
    lat: 0.4,
    lon: 37.9,
    kind: "country",
    parentId: "africa",
    childId: "nairobi",
    summary: "Equatorial highlands and the Rift Valley. Nairobi is the default city.",
    stats: [
      { label: "Region", value: "East Africa" },
      { label: "Next lock", value: "Nairobi" },
    ],
  },
  {
    id: "nigeria",
    name: "Nigeria",
    lat: 9.1,
    lon: 8.7,
    kind: "country",
    parentId: "africa",
    childId: "lagos",
    summary: "Gulf of Guinea state. Lagos is the default coastal lock.",
    stats: [
      { label: "Region", value: "West Africa" },
      { label: "Next lock", value: "Lagos" },
    ],
  },
  {
    id: "south-africa",
    name: "South Africa",
    lat: -29,
    lon: 25,
    kind: "country",
    parentId: "africa",
    childId: "cape-town",
    summary: "Southern tip of the continent, from the highveld to the Cape.",
    stats: [
      { label: "Region", value: "Southern Africa" },
      { label: "Next lock", value: "Cape Town" },
    ],
  },
  {
    id: "egypt",
    name: "Egypt",
    lat: 26.8,
    lon: 30.8,
    kind: "country",
    parentId: "africa",
    childId: "cairo",
    summary: "Nile corridor between the Mediterranean and the Red Sea.",
    stats: [
      { label: "Region", value: "North Africa" },
      { label: "Next lock", value: "Cairo" },
    ],
  },
  {
    id: "japan",
    name: "Japan",
    lat: 36.4,
    lon: 138.3,
    kind: "country",
    parentId: "asia",
    childId: "tokyo",
    summary: "Island arc off East Asia. City nodes cluster on Honshu.",
    stats: [
      { label: "Region", value: "East Asia" },
      { label: "Next lock", value: "Tokyo" },
    ],
  },
  {
    id: "india",
    name: "India",
    lat: 22.5,
    lon: 79,
    kind: "country",
    parentId: "asia",
    childId: "mumbai",
    summary: "South Asian subcontinent. Mumbai is the default city lock.",
    stats: [
      { label: "Region", value: "South Asia" },
      { label: "Next lock", value: "Mumbai" },
    ],
  },
  {
    id: "china",
    name: "China",
    lat: 35.5,
    lon: 103.5,
    kind: "country",
    parentId: "asia",
    childId: "shanghai",
    summary: "East Asian landmass. The default city lock is the Yangtze delta.",
    stats: [
      { label: "Region", value: "East Asia" },
      { label: "Next lock", value: "Shanghai" },
    ],
  },
  {
    id: "united-states",
    name: "United States",
    lat: 39.8,
    lon: -98.6,
    kind: "country",
    parentId: "north-america",
    childId: "new-york",
    summary: "Continental interior with coastal city nodes on both oceans.",
    stats: [
      { label: "Region", value: "North America" },
      { label: "Next lock", value: "New York" },
    ],
  },
  {
    id: "canada",
    name: "Canada",
    lat: 56,
    lon: -96,
    kind: "country",
    parentId: "north-america",
    childId: "toronto",
    summary: "Northern half of the continent. Toronto is the default city lock.",
    stats: [
      { label: "Region", value: "North America" },
      { label: "Next lock", value: "Toronto" },
    ],
  },
  {
    id: "mexico",
    name: "Mexico",
    lat: 23.6,
    lon: -102.5,
    kind: "country",
    parentId: "north-america",
    childId: "mexico-city",
    summary: "Between the Pacific, the Gulf, and the southern deserts.",
    stats: [
      { label: "Region", value: "North America" },
      { label: "Next lock", value: "Mexico City" },
    ],
  },
  {
    id: "brazil",
    name: "Brazil",
    lat: -10.5,
    lon: -52.5,
    kind: "country",
    parentId: "south-america",
    childId: "sao-paulo",
    summary: "Atlantic state spanning the Amazon basin and the southern plateau.",
    stats: [
      { label: "Region", value: "South America" },
      { label: "Next lock", value: "São Paulo" },
    ],
  },
  {
    id: "argentina",
    name: "Argentina",
    lat: -35,
    lon: -65,
    kind: "country",
    parentId: "south-america",
    childId: "buenos-aires",
    summary: "Southern cone, from the Andes to the Río de la Plata.",
    stats: [
      { label: "Region", value: "South America" },
      { label: "Next lock", value: "Buenos Aires" },
    ],
  },
  {
    id: "peru",
    name: "Peru",
    lat: -9.2,
    lon: -75,
    kind: "country",
    parentId: "south-america",
    childId: "lima",
    summary: "Pacific coast and the central Andes.",
    stats: [
      { label: "Region", value: "South America" },
      { label: "Next lock", value: "Lima" },
    ],
  },
  {
    id: "australia",
    name: "Australia",
    lat: -25.5,
    lon: 134.2,
    kind: "country",
    parentId: "oceania",
    childId: "sydney",
    summary: "Island continent. Coastal city nodes sit on the populated rim.",
    stats: [
      { label: "Region", value: "Oceania" },
      { label: "Next lock", value: "Sydney" },
    ],
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    lat: -41.2,
    lon: 174.5,
    kind: "country",
    parentId: "oceania",
    childId: "auckland",
    summary: "Twin islands in the south-west Pacific.",
    stats: [
      { label: "Region", value: "Oceania" },
      { label: "Next lock", value: "Auckland" },
    ],
  },
  {
    id: "lelystad",
    name: "Lelystad",
    lat: 52.5185,
    lon: 5.4714,
    kind: "city",
    parentId: "netherlands",
    childId: null,
    summary: "Capital of Flevoland, planned in 1967 on land reclaimed from the IJsselmeer. The town sits below sea level on the polder, with Lelystad Airport to the east.",
    stats: [
      { label: "Province", value: "Flevoland" },
      { label: "Founded", value: "1967" },
      { label: "Setting", value: "Polder" },
      { label: "Residents", value: "≈ 83,000" },
    ],
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    lat: 52.3676,
    lon: 4.9041,
    kind: "city",
    parentId: "netherlands",
    childId: null,
    summary: "Constitutional capital on the Amstel and the IJ, at the north end of the Randstad.",
    stats: [
      { label: "Role", value: "Capital" },
      { label: "Water", value: "IJ / Amstel" },
    ],
  },
  {
    id: "rotterdam",
    name: "Rotterdam",
    lat: 51.9225,
    lon: 4.4792,
    kind: "city",
    parentId: "netherlands",
    childId: null,
    summary: "North Sea port city on the Nieuwe Maas.",
    stats: [
      { label: "Role", value: "Port" },
      { label: "River", value: "Nieuwe Maas" },
    ],
  },
  {
    id: "utrecht",
    name: "Utrecht",
    lat: 52.0907,
    lon: 5.1214,
    kind: "city",
    parentId: "netherlands",
    childId: null,
    summary: "Inland hub of the Randstad, on the Kromme Rijn.",
    stats: [
      { label: "Role", value: "Inland hub" },
      { label: "Province", value: "Utrecht" },
    ],
  },
  {
    id: "groningen",
    name: "Groningen",
    lat: 53.2194,
    lon: 6.5665,
    kind: "city",
    parentId: "netherlands",
    childId: null,
    summary: "Principal city of the northern provinces.",
    stats: [
      { label: "Region", value: "North" },
      { label: "Province", value: "Groningen" },
    ],
  },
  {
    id: "berlin",
    name: "Berlin",
    lat: 52.52,
    lon: 13.405,
    kind: "city",
    parentId: "germany",
    childId: null,
    summary: "Capital on the Spree, in the northeast of the country.",
    stats: [{ label: "Role", value: "Capital" }],
  },
  {
    id: "hamburg",
    name: "Hamburg",
    lat: 53.5511,
    lon: 9.9937,
    kind: "city",
    parentId: "germany",
    childId: null,
    summary: "North Sea port on the Elbe.",
    stats: [{ label: "River", value: "Elbe" }],
  },
  {
    id: "munich",
    name: "Munich",
    lat: 48.1351,
    lon: 11.582,
    kind: "city",
    parentId: "germany",
    childId: null,
    summary: "Bavarian city north of the Alps.",
    stats: [{ label: "Region", value: "Bavaria" }],
  },
  {
    id: "paris",
    name: "Paris",
    lat: 48.8566,
    lon: 2.3522,
    kind: "city",
    parentId: "france",
    childId: null,
    summary: "Capital on the Seine, in the Paris Basin.",
    stats: [{ label: "River", value: "Seine" }],
  },
  {
    id: "lyon",
    name: "Lyon",
    lat: 45.764,
    lon: 4.8357,
    kind: "city",
    parentId: "france",
    childId: null,
    summary: "Confluence of the Rhône and the Saône.",
    stats: [{ label: "Rivers", value: "Rhône / Saône" }],
  },
  {
    id: "london",
    name: "London",
    lat: 51.5072,
    lon: -0.1276,
    kind: "city",
    parentId: "united-kingdom",
    childId: null,
    summary: "Capital on the Thames in southeast England.",
    stats: [{ label: "River", value: "Thames" }],
  },
  {
    id: "manchester",
    name: "Manchester",
    lat: 53.4808,
    lon: -2.2426,
    kind: "city",
    parentId: "united-kingdom",
    childId: null,
    summary: "Inland city in northwest England.",
    stats: [{ label: "Region", value: "Northwest England" }],
  },
  {
    id: "rome",
    name: "Rome",
    lat: 41.9028,
    lon: 12.4964,
    kind: "city",
    parentId: "italy",
    childId: null,
    summary: "Capital on the Tiber, inland from the Tyrrhenian Sea.",
    stats: [{ label: "River", value: "Tiber" }],
  },
  {
    id: "milan",
    name: "Milan",
    lat: 45.4642,
    lon: 9.19,
    kind: "city",
    parentId: "italy",
    childId: null,
    summary: "Po valley city south of the Alps.",
    stats: [{ label: "Region", value: "Lombardy" }],
  },
  {
    id: "madrid",
    name: "Madrid",
    lat: 40.4168,
    lon: -3.7038,
    kind: "city",
    parentId: "spain",
    childId: null,
    summary: "Capital on the Meseta, near the geographic center of the peninsula.",
    stats: [{ label: "Role", value: "Capital" }],
  },
  {
    id: "barcelona",
    name: "Barcelona",
    lat: 41.3874,
    lon: 2.1686,
    kind: "city",
    parentId: "spain",
    childId: null,
    summary: "Mediterranean port on the Catalan coast.",
    stats: [{ label: "Coast", value: "Mediterranean" }],
  },
  {
    id: "nairobi",
    name: "Nairobi",
    lat: -1.2921,
    lon: 36.8219,
    kind: "city",
    parentId: "kenya",
    childId: null,
    summary: "Highland capital south of the equator.",
    stats: [{ label: "Role", value: "Capital" }],
  },
  {
    id: "mombasa",
    name: "Mombasa",
    lat: -4.0435,
    lon: 39.6682,
    kind: "city",
    parentId: "kenya",
    childId: null,
    summary: "Indian Ocean port on the east coast.",
    stats: [{ label: "Coast", value: "Indian Ocean" }],
  },
  {
    id: "lagos",
    name: "Lagos",
    lat: 6.5244,
    lon: 3.3792,
    kind: "city",
    parentId: "nigeria",
    childId: null,
    summary: "Coastal megacity on the Gulf of Guinea.",
    stats: [{ label: "Coast", value: "Gulf of Guinea" }],
  },
  {
    id: "abuja",
    name: "Abuja",
    lat: 9.0765,
    lon: 7.3986,
    kind: "city",
    parentId: "nigeria",
    childId: null,
    summary: "Inland capital in the center of the country.",
    stats: [{ label: "Role", value: "Capital" }],
  },
  {
    id: "cape-town",
    name: "Cape Town",
    lat: -33.9249,
    lon: 18.4241,
    kind: "city",
    parentId: "south-africa",
    childId: null,
    summary: "Port city on the Cape Peninsula, between two oceans.",
    stats: [{ label: "Coast", value: "Cape Peninsula" }],
  },
  {
    id: "johannesburg",
    name: "Johannesburg",
    lat: -26.2041,
    lon: 28.0473,
    kind: "city",
    parentId: "south-africa",
    childId: null,
    summary: "Inland city on the Highveld.",
    stats: [{ label: "Setting", value: "Highveld" }],
  },
  {
    id: "cairo",
    name: "Cairo",
    lat: 30.0444,
    lon: 31.2357,
    kind: "city",
    parentId: "egypt",
    childId: null,
    summary: "Capital where the Nile meets the delta.",
    stats: [{ label: "River", value: "Nile" }],
  },
  {
    id: "tokyo",
    name: "Tokyo",
    lat: 35.6762,
    lon: 139.6503,
    kind: "city",
    parentId: "japan",
    childId: null,
    summary: "Capital on Tokyo Bay, on the Kantō plain.",
    stats: [{ label: "Bay", value: "Tokyo Bay" }],
  },
  {
    id: "osaka",
    name: "Osaka",
    lat: 34.6937,
    lon: 135.5023,
    kind: "city",
    parentId: "japan",
    childId: null,
    summary: "Port city on Osaka Bay.",
    stats: [{ label: "Region", value: "Kansai" }],
  },
  {
    id: "kyoto",
    name: "Kyoto",
    lat: 35.0116,
    lon: 135.7681,
    kind: "city",
    parentId: "japan",
    childId: null,
    summary: "Inland city in the Yamashiro basin.",
    stats: [{ label: "Setting", value: "Inland basin" }],
  },
  {
    id: "mumbai",
    name: "Mumbai",
    lat: 19.076,
    lon: 72.8777,
    kind: "city",
    parentId: "india",
    childId: null,
    summary: "Arabian Sea port on the west coast.",
    stats: [{ label: "Coast", value: "Arabian Sea" }],
  },
  {
    id: "delhi",
    name: "Delhi",
    lat: 28.6139,
    lon: 77.209,
    kind: "city",
    parentId: "india",
    childId: null,
    summary: "Inland capital region on the Yamuna.",
    stats: [{ label: "River", value: "Yamuna" }],
  },
  {
    id: "shanghai",
    name: "Shanghai",
    lat: 31.2304,
    lon: 121.4737,
    kind: "city",
    parentId: "china",
    childId: null,
    summary: "Yangtze delta port on the East China Sea.",
    stats: [{ label: "River", value: "Yangtze" }],
  },
  {
    id: "beijing",
    name: "Beijing",
    lat: 39.9042,
    lon: 116.4074,
    kind: "city",
    parentId: "china",
    childId: null,
    summary: "Inland capital on the north China plain.",
    stats: [{ label: "Role", value: "Capital" }],
  },
  {
    id: "new-york",
    name: "New York",
    lat: 40.7128,
    lon: -74.006,
    kind: "city",
    parentId: "united-states",
    childId: null,
    summary: "Atlantic harbor city at the mouth of the Hudson.",
    stats: [{ label: "River", value: "Hudson" }],
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    lat: 34.0522,
    lon: -118.2437,
    kind: "city",
    parentId: "united-states",
    childId: null,
    summary: "Pacific basin city on the southern California coast.",
    stats: [{ label: "Coast", value: "Pacific" }],
  },
  {
    id: "chicago",
    name: "Chicago",
    lat: 41.8781,
    lon: -87.6298,
    kind: "city",
    parentId: "united-states",
    childId: null,
    summary: "Great Lakes city at the southwest shore of Lake Michigan.",
    stats: [{ label: "Lake", value: "Michigan" }],
  },
  {
    id: "toronto",
    name: "Toronto",
    lat: 43.6532,
    lon: -79.3832,
    kind: "city",
    parentId: "canada",
    childId: null,
    summary: "City on the northwest shore of Lake Ontario.",
    stats: [{ label: "Lake", value: "Ontario" }],
  },
  {
    id: "vancouver",
    name: "Vancouver",
    lat: 49.2827,
    lon: -123.1207,
    kind: "city",
    parentId: "canada",
    childId: null,
    summary: "Pacific port between the coast mountains and the Strait of Georgia.",
    stats: [{ label: "Coast", value: "Pacific" }],
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    lat: 19.4326,
    lon: -99.1332,
    kind: "city",
    parentId: "mexico",
    childId: null,
    summary: "Highland capital in the Valley of Mexico.",
    stats: [{ label: "Setting", value: "Highland basin" }],
  },
  {
    id: "sao-paulo",
    name: "São Paulo",
    lat: -23.5558,
    lon: -46.6396,
    kind: "city",
    parentId: "brazil",
    childId: null,
    summary: "Inland plateau city near the southeast coast.",
    stats: [{ label: "Setting", value: "Plateau" }],
  },
  {
    id: "rio",
    name: "Rio de Janeiro",
    lat: -22.9068,
    lon: -43.1729,
    kind: "city",
    parentId: "brazil",
    childId: null,
    summary: "Atlantic harbor between the mountains and Guanabara Bay.",
    stats: [{ label: "Coast", value: "Atlantic" }],
  },
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    lat: -34.6037,
    lon: -58.3816,
    kind: "city",
    parentId: "argentina",
    childId: null,
    summary: "Capital on the Río de la Plata estuary.",
    stats: [{ label: "Estuary", value: "Río de la Plata" }],
  },
  {
    id: "lima",
    name: "Lima",
    lat: -12.0464,
    lon: -77.0428,
    kind: "city",
    parentId: "peru",
    childId: null,
    summary: "Pacific capital on the coastal desert.",
    stats: [{ label: "Coast", value: "Pacific" }],
  },
  {
    id: "sydney",
    name: "Sydney",
    lat: -33.8688,
    lon: 151.2093,
    kind: "city",
    parentId: "australia",
    childId: null,
    summary: "Pacific harbor city on the southeast coast.",
    stats: [{ label: "Harbor", value: "Port Jackson" }],
  },
  {
    id: "melbourne",
    name: "Melbourne",
    lat: -37.8136,
    lon: 144.9631,
    kind: "city",
    parentId: "australia",
    childId: null,
    summary: "City at the head of Port Phillip Bay.",
    stats: [{ label: "Bay", value: "Port Phillip" }],
  },
  {
    id: "auckland",
    name: "Auckland",
    lat: -36.8509,
    lon: 174.7645,
    kind: "city",
    parentId: "new-zealand",
    childId: null,
    summary: "Isthmus city between two harbors on the North Island.",
    stats: [{ label: "Island", value: "North Island" }],
  },
];

const BY_ID = new Map(LIST.map((place) => [place.id, place]));

export const DEFAULT_PATH = ["europe", "netherlands", "lelystad"] as const;

export function getPlace(id: string) {
  return BY_ID.get(id);
}

export function childrenOf(id: string) {
  return LIST.filter((place) => place.parentId === id);
}

export function resolvePath(id: string): [string, string, string] {
  const start = getPlace(id);
  if (!start) return [...DEFAULT_PATH];
  const lineage: string[] = [];
  let cursor: Place | undefined = start;
  while (cursor && lineage.length < 4) {
    lineage.unshift(cursor.id);
    cursor = cursor.parentId ? getPlace(cursor.parentId) : undefined;
  }
  const continent = lineage[0];
  const country = lineage[1] ?? getPlace(continent)?.childId;
  const city = lineage[2] ?? (country ? getPlace(country)?.childId : undefined);
  if (!continent || !country || !city) return [...DEFAULT_PATH];
  return [continent, country, city];
}

export function pathSlot(path: readonly [string, string, string], slot: 0 | 1 | 2) {
  if (slot === 0) return path[0];
  if (slot === 1) return path[1];
  return path[2];
}

export function levelForKind(kind: PlaceKind): 1 | 2 | 3 {
  if (kind === "continent") return 1;
  if (kind === "country") return 2;
  return 3;
}

export function ancestorChain(id: string) {
  const names: string[] = [];
  let cursor = getPlace(id);
  while (cursor) {
    names.unshift(cursor.name);
    cursor = cursor.parentId ? getPlace(cursor.parentId) : undefined;
  }
  return names;
}

export const FLOATING_LABELS = [
  { id: "infra", text: "GLOBAL\nINFRASTRUCTURE", position: [-1.15, 0.62, 2.15] as [number, number, number], target: "europe", priority: true },
  { id: "explore", text: "EXPLORE", position: [1.15, 0.08, 2.25] as [number, number, number], target: "netherlands", priority: true },
  { id: "continents", text: "CONTINENTS", position: [-1.05, -0.62, 2.2] as [number, number, number], target: "africa", priority: true },
  { id: "networks", text: "NETWORKS", position: [1.05, 0.72, 1.9] as [number, number, number], target: "japan", priority: false },
  { id: "cities", text: "CITIES", position: [0.1, -0.82, 2.3] as [number, number, number], target: "amsterdam", priority: false },
] as const;
